# Generated by Django 5.2.12 on 2026-03-14 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_appearance',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_satiety',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_taste',
        ),
        migrations.RemoveField(
            model_name='post',
            name='saves_count',
        ),
        migrations.AddField(
            model_name='post',
            name='dish_name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='appearance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Внешний вид'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='satiety',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Сытность'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='taste',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postsave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_taste', models.FloatField(default=0.0, verbose_name='Оценка за вкус')),
                ('rating_appearance', models.FloatField(default=0.0, verbose_name='Оценка за внешний вид')),
                ('rating_satiety', models.FloatField(default=0.0, verbose_name='Оценка за сытность')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('saves_count', models.PositiveIntegerField(default=0, verbose_name='Количество сохранений')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='posts.post')),
            ],
        ),
    ]
