# Generated by Django 5.2.12 on 2026-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststatistics',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
