# Generated by Django 5.2.12 on 2026-03-15 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_poststatistics_comments_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='posts_comme_created_d006cd_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['-created_at'], name='posts_postl_created_8fd2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='postreview',
            index=models.Index(fields=['-created_at'], name='posts_postr_created_7b078a_idx'),
        ),
        migrations.AddIndex(
            model_name='postsave',
            index=models.Index(fields=['-created_at'], name='posts_posts_created_54dc93_idx'),
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['-created_at'], name='posts_postt_created_b1a753_idx'),
        ),
    ]
