# Generated by Django 5.2.12 on 2026-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_dish_restaurant_tag_usage_count_post_dish_dishtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
    ]
