# Generated by Django 5.2.12 on 2026-03-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_dish_name_alter_restaurant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dish_name',
        ),
    ]
